let a = 10;
let b = 20;
let c;
c = a + b;
console.log("Add:", c);
c = a - b;
console.log("Sub:", c);
c = a * b;
console.log("Mul:", c);
c = a / b;
console.log("Div:", c);
c = a % b;
console.log("Mod:", c);
c = a ** b;
console.log("Expo:", c);
c = a++;
console.log("Post-increment:", c);
c = ++a;
console.log("Pre-increment:", c);
c = a--;
console.log("Post-decrement:", c);
c = --a;
console.log("Pre-decrement:", c);
c = a == b;
console.log("Equality:", c);
c = a != b;
console.log("Inequality:", c);
c = a === b;
console.log("Strict Equality:", c);
c = a !== b;
console.log("Strict Inequality:", c);
c = a > b;
console.log("Greater than:", c);
c = a < b;
console.log("Less than:", c);
c = a >= b;
console.log("Greater than or equal to:", c);
c = a <= b;
console.log("Less than or equal to:", c);
